import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Recipe Tool</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          My Recipes
        </h1>

        <div className="search-bar">
          <img src="/search_icon.svg" />
          <p>Search Recipes</p>
        </div>

        <div className="tags">
          <p className='tag'>All</p>
          <p className='tag'>Breakfast</p>
          <p className='tag'>Lunch</p>
          <p className='tag'>Dinner</p>
          <p className='tag'>Dessert</p>
          <p className='tag'>Smoothies</p>
        </div>

        <div className="recipe-list">
          <div>
            <img src="/recipe_thumbnail.png" className='recipe-thumbnail'/>
            <h2 className='recipe-title'>Flavorful Dan Dan Mian Noodles </h2>
            <div className='user-info'>
              <img src="/profile.png">
              </img>
              <p className='author-name'>Leslie Alex</p>
            </div>
          </div>

          <div className='divider'></div>
        </div>
      </main>
    </div>
  )
}
